[pytest]
markers =
    smoke: 冒烟测试用例
    regression: 回归测试用例
    metrics: 模型指标测试用例
    drift: 数据漂移测试用例
    mine: 自定义测试用例
    mycase: 自定义测试用例
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v